services:

  # LLM model
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/Sao_Paulo}
      - UMASK=002
      - NVIDIA_VISIBLE_DEVICES=0 # Comma separated list of GPU IDs
    volumes:
      - ${PATH_CACHE}/ollama:/root/.ollama
    ports:
      - "11434:11434"
    devices: 
      - "/dev/nvidia0:/dev/nvidia0" # Expose the GPU device
    restart: always

  # Web UI
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/Sao_Paulo}
      - UMASK=002
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./open-webui:/app/backend/data
      - ${PATH_CACHE}/open-webui:/app/backend/data/cache
    ports:
      - "${PORT_WEBUI:-8080}:8080"
    restart: always
