services:

  # LLM model
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/Sao_Paulo}
      - UMASK=002
    volumes:
      - ${PATH_CACHE}/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  # Web UI
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/Sao_Paulo}
      - UMASK=002
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - "${PORT_WEBUI:-8080}:8080"
    restart: always

